### ISSUE TITLE
Evaluate & Merge Event 38's Mission Planner Improvements

### ISSUE THREAD

**Issue by edwinhayes** [Aeronavics/MissionPlanner#5]
http://diydrones.com/profiles/blogs/new-event-38-mission-planner-features

Download a copy of their version, and check out the changes, then probably show them to everyone else at at meeting and see if we want any of them.  If so, contact Jeff Taylor, see if their changes have already been merged into the mainline, and if not, ask if we can get a copy so that we can have them.

**Comment by JWangAeronavics** [comment]
Mission planner already supports a pre-flight checklist that is user customisable with values e.g. battery voltages appropriate for the airframe and the in flight monitoring is not particularly well implemented (stuck in the menubar rather than a movable window near the HUD). More worthwhile reimplementing this ourselves
